apiVersion: v1
kind: Service
metadata:
  name: patient-record-service
spec:
  selector:
    app: patient-record-service-green  # Initially set to green
  ports:
  - protocol: TCP
    port: 80
    targetPort: 30001
  type: ClusterIP
