apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-record-service-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-record-service-green
  template:
    metadata:
      labels:
        app: patient-record-service-green
    spec:
      containers:
      - name: patient-record-service
        image: gcr.io/healthsync-project-445302/patient-record-service:latest
        resources:
          limits:
            cpu: "500m"
            memory: "128Mi"
          requests:
            cpu: "250m"
            memory: "64Mi"
        ports:
        - containerPort: 3001
        livenessProbe: null
        readinessProbe: null
        # readinessProbe:
        #   httpGet:
        #     path: /api/v1/patient-record-service/readiness
        #     port: 3001
        #   initialDelaySeconds: 40
        #   periodSeconds: 10
        # livenessProbe:
        #   httpGet:
        #     path: /api/v1/patient-record-service/healthcheck
        #     port: 3001
        #   initialDelaySeconds: 40
        #   periodSeconds: 10
        env:
        - name: MONGO_URI
          value: "mongodb+srv://navodasathsarani:chQf3ctN1Xwx7H6s@health-sync-mongo-db.okigg.mongodb.net/health-db?retryWrites=true&w=majority&appName=health-sync-mongo-db"
