swagger: "2.0"
info:
  title: "Patient Record Service API"
  description: "API Gateway for Patient Record Service"
  version: "1.0.0"
host: "{GATEWAY_ID}.gateway.dev"
x-google-backend:
  address: http://<CLUSTER_EXTERNAL_IP>:80
paths:
  /patients:
    get:
      summary: "Get patient records"
      operationId: "getPatients"
      responses:
        '200':
          description: "A list of patients"
    post:
      summary: "Add a new patient record"
      operationId: "addPatient"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            type: "object"
            properties:
              name:
                type: "string"
              age:
                type: "integer"
              gender:
                type: "string"
      responses:
        '201':
          description: "Patient record created successfully"
