apiVersion: v1
kind: Service
metadata:
  name: patient-record-service
spec:
  selector:
    app: patient-record-service
  ports:
  - protocol: TCP
    port: 30001
    targetPort: 30001
  type: ClusterIP
